sudo: required
services:
  - docker

before_install:
  - docker build -t abhole/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run abhole/react-test npm test -- --coverage

after_success:
  - docker build -t abhole/multi-client ./client
  - docker build -t abhole/multi-nginx ./nginx
  - docker build -t abhole/multi-server ./server
  - docker build -t abhole/multi-worker ./worker
# login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push abhole/multi-client
  - docker push abhole/multi-nginx
  - docker push abhole/multi-server
  - docker push abhole/multi-worker
